CLASS LHC_ZSTUR_CIT_DB_22CZ301301 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZsturCitDb22cz301301
        RESULT result.
ENDCLASS.

CLASS LHC_ZSTUR_CIT_DB_22CZ301301 IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
ENDCLASS.
